# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'pskdev'
  imageName: 'frontend'

steps:
  - script: |
      docker build -t repo.treescale.com/$(dockerId)/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword) repo.treescale.com
      docker push repo.treescale.com/$(dockerId)/$(imageName)
    env:
      pswd: $(dockerPassword)
