version: '3'
services:

  backend:
    image: repo.treescale.com/pskdev/pskdev/backend:latest
    container_name: fe_backend
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mongo:4.0
    container_name: fe_db
    ports:
      - 27017:27017
    volumes:
      - db_mongo_data:/data/db

volumes:
  db_mongo_data:
    driver: local
